"""init migration

Revision ID: 2de5ee3f17c4
Revises:
Create Date: 2023-06-17 00:42:21.958659

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2de5ee3f17c4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("players", sa.Column("id", sa.UUID(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_table(
        "elos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.String(length=255), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("elo", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("elos")
    op.drop_table("players")
    op.drop_table("matches")
    # ### end Alembic commands ###
