"""bet_matches match_id

Revision ID: bf0515f96474
Revises: 23843d492270
Create Date: 2023-10-23 15:35:38.392158

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf0515f96474"
down_revision = "23843d492270"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bet_matches_match_id_fkey", "bet_matches", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("bet_matches_match_id_fkey", "bet_matches", "matches", ["match_id"], ["id"])
    # ### end Alembic commands ###
