"""member_id to string

Revision ID: 815d2c091134
Revises: bf0515f96474
Create Date: 2023-10-30 21:15:14.373495

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "815d2c091134"
down_revision = "bf0515f96474"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bet_events", "member_id", existing_type=sa.INTEGER(), type_=sa.String(length=64), existing_nullable=False
    )
    op.alter_column(
        "bet_matches",
        "match_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "bet_transactions",
        "member_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bet_transactions",
        "member_id",
        existing_type=sa.String(length=64),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "bet_matches",
        "match_id",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "bet_events", "member_id", existing_type=sa.String(length=64), type_=sa.INTEGER(), existing_nullable=False
    )
    # ### end Alembic commands ###
