repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
  - id: ruff-check
    name: ruff-check
    entry: ruff check --fix --force-exclude
    language: python
    types_or: [python]
    args: [ ]
    require_serial: true
  - id: ruff-format
    name: ruff-format
    entry: ruff format --force-exclude
    types_or: [python]
    require_serial: true
    args: []
    language: python
