"""added game to matches

Revision ID: 841bfcff275a
Revises: 2de5ee3f17c4
Create Date: 2023-09-28 23:02:06.158484

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "841bfcff275a"
down_revision = "2de5ee3f17c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("game", sa.String(length=64), server_default="csgo", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "game")
    # ### end Alembic commands ###
